const state = { token: sessionStorage.getItem('nilam_admin_token') || '', permissions: [], products: [], categories: [], collections: [], edit: null }
const $ = selector => document.querySelector(selector)
const content = $('#page-content')
const pages = { '/dashboard': ['Overview', 'ERP control centre'], '/products': ['Products', 'Catalogue'], '/categories': ['Categories', 'Catalogue structure'], '/collections': ['Collections', 'Merchandising'], '/inventory': ['Inventory', 'Stock control'] }
const escapeHtml = value => { const element = document.createElement('span'); element.textContent = String(value ?? ''); return element.innerHTML }
const rupiah = value => 'Rp ' + Number(value || 0).toLocaleString('id-ID')
const applyPermissions = permissions => { state.permissions = permissions || []; document.querySelectorAll('[data-permission]').forEach(item => { item.hidden = !state.token && !state.permissions.includes(item.dataset.permission) }) }

async function api(path, options = {}) {
  const response = await fetch('/api/admin' + path, { ...options, headers: { 'x-admin-token': state.token, 'content-type': 'application/json', ...(options.headers || {}) } })
  if (!response.ok) { const body = await response.json().catch(() => ({})); if (response.status === 401 && !state.token) { $('#app-view').hidden = true; $('#login-view').hidden = false; $('#login-error').textContent = 'Your staff session has expired. Please sign in again.' } if (response.status === 403) { content.innerHTML = '<div class="empty-state"><h2>Access denied</h2><p>You do not have permission for this ERP area. Contact an authorised administrator if you need access.</p></div>' } throw new Error(body.message || 'Request failed (' + response.status + ')') }
  return response.status === 204 ? null : response.json()
}
async function uploadMedia(path, form) {
  const response = await fetch('/api/admin' + path, { method: 'POST', headers: { 'x-admin-token': state.token }, body: new FormData(form) })
  if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.message || 'Upload failed (' + response.status + ')') }
  return response.json()
}
function notify(message, error = false) { const node = $('#toast'); node.textContent = message; node.className = 'toast' + (error ? ' toast-error' : ''); node.hidden = false; clearTimeout(notify.timer); notify.timer = setTimeout(() => { node.hidden = true }, 3500) }
function table(head, rows) { return '<div class="table-wrap"><table><thead><tr>' + head.map(item => '<th>' + item + '</th>').join('') + '</tr></thead><tbody>' + rows + '</tbody></table></div>' }
function activeNav(path) { document.querySelectorAll('[data-route]').forEach(item => item.classList.toggle('active', item.dataset.route === path)) }
function go(path) { const route = pages[path] ? path : '/dashboard'; if (location.pathname !== route) history.pushState({}, '', route); render() }
function loading() { content.innerHTML = '<div class="empty-state"><span class="spinner"></span><p>Loading workspace…</p></div>' }

async function dashboard() {
  const data = await api('/dashboard')
  const cards = [['Net sales', rupiah(data.netSales)], ['Orders', data.orderCount], ['Active products', data.productCount], ['Low stock', data.lowStock], ['Managed WebP media', data.media?.managed || 0], ['Legacy media', data.media?.legacy || 0]]
  content.innerHTML = '<section class="metrics">' + cards.map(card => '<article class="metric"><span>' + card[0] + '</span><strong>' + card[1] + '</strong><small>Current environment</small></article>').join('') + '</section><section class="dashboard-grid"><article class="panel"><p class="eyebrow">Quick actions</p><h2>Keep the catalogue moving</h2><p class="muted">Manage all product images as WebP files from the product editor.</p><div class="button-row"><button data-go="/products">Manage products</button><button class="secondary" data-go="/inventory">Adjust stock</button></div></article><article class="panel"><p class="eyebrow">Media migration</p><h2>' + (data.media?.legacy || 0) + ' legacy records</h2><p class="muted">Legacy files are not served publicly. Replace them through each product’s media manager.</p></article><article class="panel"><p class="eyebrow">Order queue</p><h2>' + data.pendingOrders + ' pending orders</h2><p class="muted">Order management will appear here as orders arrive.</p></article></section>'
}

function productRows(items) { return items.length ? items.map(item => '<tr><td><strong>' + escapeHtml(item.name) + '</strong><br><small>/' + escapeHtml(item.handle) + '</small></td><td>' + escapeHtml(item.category) + '</td><td><span class="status ' + String(item.status).toLowerCase() + '">' + escapeHtml(item.status) + '</span></td><td>' + item.stock + '</td><td><button class="secondary small" data-edit-product="' + item.id + '">Edit</button></td></tr>').join('') : '<tr><td colspan="5">No products found.</td></tr>' }
async function products() {
  state.products = await api('/products')
  content.innerHTML = '<section class="panel"><div class="panel-heading"><div><p class="eyebrow">Catalogue</p><h2>Products</h2><p class="muted">Manage product details, publishing status, and stock.</p></div><div class="product-actions"><input id="product-search" type="search" placeholder="Search products" /><button id="new-product" type="button">New product</button></div></div>' + table(['Product', 'Category', 'Status', 'Stock', ''], productRows(state.products)) + '</section>'
  $('#new-product').addEventListener('click', () => openProduct())
  $('#product-search').addEventListener('input', event => { const q = event.target.value.toLowerCase(); content.querySelector('tbody').innerHTML = productRows(state.products.filter(item => item.name.toLowerCase().includes(q) || item.handle.toLowerCase().includes(q))) })
}

function manager(kind, items) {
  const isCollection = kind === 'collections'; const singular = isCollection ? 'Collection' : 'Category'; const edit = state.edit || {}
  const description = isCollection ? '<label>Description<input name="description" value="' + escapeHtml(edit.description || '') + '" /></label>' : ''
  const rows = items.length ? items.map(item => '<tr><td><strong>' + escapeHtml(item.name) + '</strong></td><td>/' + escapeHtml(item.handle) + '</td>' + (isCollection ? '<td>' + escapeHtml(item.description || '—') + '</td>' : '') + '<td>' + item._count.products + '</td><td><button class="secondary small" data-edit-' + kind + '="' + item.id + '">Edit</button> <button class="danger small" data-delete-' + kind + '="' + item.id + '">Delete</button></td></tr>').join('') : '<tr><td colspan="5">No ' + kind + ' yet.</td></tr>'
  const headers = isCollection ? ['Collection', 'Handle', 'Description', 'Products', ''] : ['Category', 'Handle', 'Products', '']
  content.innerHTML = '<section class="panel"><div class="panel-heading"><div><p class="eyebrow">' + (isCollection ? 'Merchandising' : 'Catalogue structure') + '</p><h2>' + singular + ' management</h2></div></div><form id="manager-form" class="inline-form"><label>Name<input name="name" required value="' + escapeHtml(edit.name || '') + '" /></label><label>Handle<input name="handle" required pattern="[a-z0-9-]+" value="' + escapeHtml(edit.handle || '') + '" /></label>' + description + '<div class="form-actions"><button>' + (edit.id ? 'Save changes' : 'Add ' + singular.toLowerCase()) + '</button>' + (edit.id ? '<button class="secondary" id="cancel-edit" type="button">Cancel</button>' : '') + '</div></form><p id="manager-error" class="error" role="alert"></p>' + table(headers, rows) + '</section>'
  $('#manager-form').addEventListener('submit', async event => { event.preventDefault(); try { await api('/' + kind + (edit.id ? '/' + edit.id : ''), { method: edit.id ? 'PATCH' : 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); state.edit = null; notify(edit.id ? 'Changes saved.' : singular + ' added.'); render() } catch (error) { $('#manager-error').textContent = error.message } })
  $('#cancel-edit')?.addEventListener('click', () => { state.edit = null; render() })
}
async function inventory() { const items = await api('/inventory'); const rows = items.length ? items.map(item => '<tr><td><strong>' + escapeHtml(item.product) + '</strong>' + (item.lowStock ? '<br><small class="error">Low stock</small>' : '') + '</td><td>' + escapeHtml(item.variant) + '<br><small>' + escapeHtml(item.sku) + '</small></td><td><form class="stock-editor" data-variant="' + item.id + '"><label>On hand<input name="quantity" type="number" min="0" step="1" value="' + item.quantity + '" /></label><label>Low-stock at<input name="lowStockThreshold" type="number" min="0" step="1" value="' + item.lowStockThreshold + '" /></label><label>Reason<input name="reason" required maxlength="160" placeholder="Delivery received" /></label><button class="small">Save</button><button class="secondary small" type="button" data-history="' + item.id + '">History</button></form></td></tr>').join('') : '<tr><td colspan="3">No inventory records found.</td></tr>'; content.innerHTML = '<section class="panel"><div class="panel-heading"><div><p class="eyebrow">Stock control</p><h2>Inventory</h2><p class="muted">Every saved change records a before/after movement and reason.</p></div></div>' + table(['Product', 'Variant / SKU', 'Stock control'], rows) + '</section>'; document.querySelectorAll('.stock-editor').forEach(form => form.addEventListener('submit', async event => { event.preventDefault(); try { const values = Object.fromEntries(new FormData(form)); await api('/inventory/' + form.dataset.variant, { method: 'PATCH', body: JSON.stringify({ quantity: Number(values.quantity), lowStockThreshold: Number(values.lowStockThreshold), reason: values.reason }) }); notify('Inventory updated.'); render() } catch (error) { notify(error.message, true) } })); document.querySelectorAll('[data-history]').forEach(button => button.addEventListener('click', async () => { try { const movements = await api('/inventory/' + button.dataset.history + '/movements'); const text = movements.length ? movements.map(item => new Date(item.createdAt).toLocaleString() + ': ' + (item.delta >= 0 ? '+' : '') + item.delta + ' (' + item.previousQuantity + ' → ' + item.quantity + ') — ' + item.reason).join('\n') : 'No adjustments recorded yet.'; alert(text) } catch (error) { notify(error.message, true) } })) }

async function render() { const path = pages[location.pathname] ? location.pathname : '/dashboard'; if (path !== location.pathname) history.replaceState({}, '', path); const meta = pages[path]; $('#page-title').textContent = meta[0]; $('#page-eyebrow').textContent = meta[1]; activeNav(path); loading(); try { if (path === '/dashboard') await dashboard(); if (path === '/products') await products(); if (path === '/categories' || path === '/collections') manager(path.slice(1), await api(path)); if (path === '/inventory') await inventory() } catch (error) { content.innerHTML = '<div class="empty-state"><h2>Unable to load this page</h2><p>' + escapeHtml(error.message) + '</p><button onclick="location.reload()">Try again</button></div>' } }

async function refreshProductDialog(productId) { state.products = await api('/products'); await openProduct(state.products.find(item => item.id === productId)) }
function renderVariantManager(product) { const section = $('#variant-manager'); section.hidden = !product; if (!product) return; const rows = product.variants.map(variant => '<form class="variant-editor" data-variant="' + variant.id + '"><input name="name" value="' + escapeHtml(variant.name) + '" required /><input name="sku" value="' + escapeHtml(variant.sku) + '" required /><input name="price" type="number" min="0" step="1" value="' + variant.price + '" required /><span>' + (variant.inventory?.quantity || 0) + ' on hand</span><button class="secondary small">Save</button><button class="danger small" type="button" data-delete-variant="' + variant.id + '">Delete</button></form>').join(''); section.innerHTML = '<h3>Variants</h3><p class="muted">Stock is adjusted from Inventory to retain a movement history.</p><div class="variant-grid">' + rows + '</div><form id="new-variant" class="variant-editor"><input name="name" placeholder="Style / colour" required /><input name="sku" placeholder="SKU" required /><input name="price" type="number" min="0" step="1" placeholder="Price (IDR)" required /><input name="quantity" type="number" min="0" step="1" value="0" required /><button class="small">Add variant</button></form>'; section.querySelectorAll('.variant-editor[data-variant]').forEach(form => form.addEventListener('submit', async event => { event.preventDefault(); try { const values = Object.fromEntries(new FormData(form)); await api('/products/' + product.id + '/variants/' + form.dataset.variant, { method: 'PATCH', body: JSON.stringify(values) }); notify('Variant saved.'); refreshProductDialog(product.id) } catch (error) { notify(error.message, true) } })); section.querySelectorAll('[data-delete-variant]').forEach(button => button.addEventListener('click', async () => { if (!confirm('Delete this variant?')) return; try { await api('/products/' + product.id + '/variants/' + button.dataset.deleteVariant, { method: 'DELETE' }); notify('Variant deleted.'); refreshProductDialog(product.id) } catch (error) { notify(error.message, true) } })); $('#new-variant').addEventListener('submit', async event => { event.preventDefault(); try { await api('/products/' + product.id + '/variants', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); notify('Variant added.'); refreshProductDialog(product.id) } catch (error) { notify(error.message, true) } }) }
function renderMediaManager(product) { const section = $('#media-manager'); section.hidden = !product; if (!product) return; const media = product.media || []; const rows = media.length ? media.map(item => '<article class="media-item"><img src="' + escapeHtml(item.url) + '" alt="" /><form data-media="' + item.id + '"><label>Alt text<input name="alt" value="' + escapeHtml(item.alt) + '" required /></label><label>Position<input name="position" type="number" min="0" step="1" value="' + item.position + '" required /></label><button class="secondary small">Save</button><button class="danger small" type="button" data-delete-media="' + item.id + '">Delete</button></form></article>').join('') : '<p class="muted">No stored media yet. Legacy URL images must be replaced with a local upload before launch.</p>'; section.innerHTML = '<h3>Product media</h3><p class="muted">Uploads are converted to WebP and stored in the private bucket workflow. JPEG, PNG, or WebP source files only; maximum 10 MB.</p><div class="media-grid">' + rows + '</div><form id="media-upload" class="media-upload"><label>Image file<input name="file" type="file" accept="image/jpeg,image/png,image/webp" required /></label><label>Alt text<input name="alt" required value="' + escapeHtml(product.name) + '" /></label><button class="small">Upload WebP</button></form>'; section.querySelectorAll('form[data-media]').forEach(form => form.addEventListener('submit', async event => { event.preventDefault(); try { await api('/products/' + product.id + '/media/' + form.dataset.media, { method: 'PATCH', body: JSON.stringify(Object.fromEntries(new FormData(form))) }); notify('Media saved.'); refreshProductDialog(product.id) } catch (error) { notify(error.message, true) } })); section.querySelectorAll('[data-delete-media]').forEach(button => button.addEventListener('click', async () => { if (!confirm('Delete this media object? This cannot be undone.')) return; try { await api('/products/' + product.id + '/media/' + button.dataset.deleteMedia, { method: 'DELETE' }); notify('Media deleted.'); refreshProductDialog(product.id) } catch (error) { notify(error.message, true) } })); $('#media-upload').addEventListener('submit', async event => { event.preventDefault(); try { await uploadMedia('/products/' + product.id + '/media', event.currentTarget); notify('WebP media uploaded.'); refreshProductDialog(product.id) } catch (error) { notify(error.message, true) } }) }
async function openProduct(product) { try { [state.categories, state.collections] = await Promise.all([api('/categories'), api('/collections')]); $('#product-form').reset(); $('#product-id').value = product?.id || ''; $('#product-name').value = product?.name || ''; $('#product-handle').value = product?.handle || ''; $('#product-description').value = product?.description || ''; $('#product-status').value = product?.status || 'DRAFT'; $('#product-category').innerHTML = state.categories.map(item => '<option value="' + item.id + '">' + escapeHtml(item.name) + '</option>').join(''); if (product) $('#product-category').value = state.categories.find(item => item.name === product.category)?.id || ''; const selectedCollections = new Set((product?.collections || []).map(item => item.collectionId)); $('#product-collections').innerHTML = state.collections.length ? state.collections.map(item => '<label class="check-option"><input type="checkbox" value="' + item.id + '"' + (selectedCollections.has(item.id) ? ' checked' : '') + ' /> ' + escapeHtml(item.name) + '</label>').join('') : '<small>Create a collection first to assign products.</small>'; $('#product-dialog-title').textContent = product ? 'Edit product' : 'New product'; document.querySelectorAll('.new-only').forEach(node => { node.hidden = Boolean(product); node.querySelectorAll('input').forEach(input => { input.required = !product && input.id !== 'product-image' }) }); renderVariantManager(product); renderMediaManager(product); $('#product-dialog').showModal() } catch (error) { notify(error.message, true) } }

document.addEventListener('click', event => { const target = event.target.closest('[data-route], [data-go], [data-edit-product], [data-edit-categories], [data-edit-collections], [data-delete-categories], [data-delete-collections]'); if (!target) return; if (target.dataset.route) { event.preventDefault(); go(target.dataset.route); return } if (target.dataset.go) { go(target.dataset.go); return } if (target.dataset.editProduct) { openProduct(state.products.find(item => item.id === target.dataset.editProduct)); return } const kind = target.dataset.editCategories || target.dataset.deleteCategories ? 'categories' : 'collections'; const id = target.dataset.editCategories || target.dataset.editCollections || target.dataset.deleteCategories || target.dataset.deleteCollections; if (target.dataset.deleteCategories || target.dataset.deleteCollections) { if (confirm('Delete this item?')) api('/' + kind + '/' + id, { method: 'DELETE' }).then(() => { notify('Deleted.'); render() }).catch(error => notify(error.message, true)) } else api('/' + kind).then(items => { state.edit = items.find(item => item.id === id); render() }) })
$('#login-form').addEventListener('submit', async event => { event.preventDefault(); try { const response = await fetch('/api/erp/auth/login', { method: 'POST', headers: { 'content-type': 'application/json', 'x-csrf-token': document.cookie.split('; ').find(value => value.startsWith('nilam_csrf='))?.split('=')[1] || '' }, body: JSON.stringify({ email: $('#email-input').value, password: $('#password-input').value }) }); const body = await response.json(); if (!response.ok) throw new Error(body.message || 'Unable to sign in'); applyPermissions(body.permissions); $('#login-view').hidden = true; $('#app-view').hidden = false; go('/dashboard') } catch (error) { $('#login-error').textContent = error.message || 'Unable to sign in.' } })
$('#sign-out').addEventListener('click', () => { sessionStorage.removeItem('nilam_admin_token'); state.token = ''; $('#app-view').hidden = true; $('#login-view').hidden = false; history.replaceState({}, '', '/') })
document.querySelectorAll('.close-dialog').forEach(button => button.addEventListener('click', () => $('#product-dialog').close()))
$('#product-form').addEventListener('submit', async event => { event.preventDefault(); const id = $('#product-id').value; try { const body = Object.fromEntries(new FormData(event.currentTarget)); body.collectionIds = Array.from(document.querySelectorAll('#product-collections input:checked')).map(input => input.value); await api('/products' + (id ? '/' + id : ''), { method: id ? 'PATCH' : 'POST', body: JSON.stringify(body) }); $('#product-dialog').close(); notify(id ? 'Product updated.' : 'Product created.'); go('/products') } catch (error) { $('#product-error').textContent = error.message } })
window.addEventListener('popstate', render)
async function restoreSession() { if (state.token) { applyPermissions([]); $('#login-view').hidden = true; $('#app-view').hidden = false; render(); return } try { const response = await fetch('/api/erp/auth/session'); const body = await response.json(); if (body.staff) { applyPermissions(body.permissions); $('#login-view').hidden = true; $('#app-view').hidden = false; render() } } catch { /* Keep the sign-in screen available when the API is unreachable. */ } }
void restoreSession()
