import { useState } from 'react'
import { FiChevronDown } from 'react-icons/fi'
import type { Product } from '../../types/product'
import { ProductCard } from '../ProductCard'
import './editorial.css'
import './editorial-placeholders.css'

export function StoryCard({ eyebrow, title, copy, image, reverse = false }: { eyebrow: string; title: string; copy: string; image?: string; reverse?: boolean }) { return <article className={`story-card ${reverse ? 'story-card-reverse' : ''}`}>{image ? <img src={image} alt="" loading="lazy" /> : <div className="story-placeholder" aria-hidden="true">Nilam</div>}<div><p className="eyebrow">{eyebrow}</p><h3>{title}</h3><p>{copy}</p></div></article> }
export function ProductPrinciples() { const principles = [['Easy movement', 'Shapes designed to accompany a full day.'], ['Considered cloth', 'Soft hand-feel and details selected with care.'], ['Made to keep', 'Pieces that layer, return, and live beyond one season.']]; return <section className="principles" aria-label="Nilam product principles">{principles.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</section> }
export function StyleExplorer({ products }: { products: Product[] }) { const moods = [{ label: 'Warm', undertone: 'warm', copy: 'Sunlit creams and rose tones for a soft, luminous feeling.' }, { label: 'Neutral', undertone: 'neutral', copy: 'Balanced olives and grounded shades that work across the day.' }, { label: 'Cool', undertone: 'cool', copy: 'Quiet sage and fresh tones for a calm, clear finish.' }]; const [selected, setSelected] = useState(0); const mood = moods[selected]; const choices = products.filter(product => product.undertone === mood.undertone).slice(0, 2); return <section className="style-explorer"><div><p className="eyebrow">Find your feeling</p><h2>Dress for the shape of your day.</h2><div className="mood-tabs" role="tablist" aria-label="Undertone choices">{moods.map((item, index) => <button key={item.label} role="tab" aria-selected={selected === index} className={selected === index ? 'active' : ''} onClick={() => setSelected(index)}>{item.label}</button>)}</div><p>{mood.copy}</p></div><div className="style-products">{choices.length ? choices.map(product => <ProductCard key={product.id} product={product} />) : <p>New pieces for this undertone are arriving soon.</p>}</div></section> }
export function FaqAccordion() { const entries = [['How do I choose a piece?', 'Start with how you want to move through the day, then choose the fabric, colour, and silhouette that feel most like you.'], ['Will more colours arrive?', 'Yes. We add considered colour stories in small, intentional releases.'], ['Where can I see Nilam in person?', 'Use our store locator to find current locations and opening details.']]; const [open, setOpen] = useState<number | null>(0); return <section className="faq"><div><p className="eyebrow">A little help</p><h2>Questions, gently answered.</h2></div><div>{entries.map(([question, answer], index) => <article key={question}><button aria-expanded={open === index} onClick={() => setOpen(open === index ? null : index)}>{question}<FiChevronDown /></button>{open === index && <p>{answer}</p>}</article>)}</div></section> }
