import { useState } from 'react'
import { FiArrowRight, FiInstagram, FiMapPin, FiMessageCircle } from 'react-icons/fi'
import { Link } from 'react-router-dom'

export function Footer() {
  const [email, setEmail] = useState(''); const [message, setMessage] = useState('')
  const subscribe = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch('/api/newsletter', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email }) }); const body = await response.json(); setMessage(response.ok ? 'Thank you — you are on the list.' : body.message || 'Unable to subscribe.') }
  return <footer id="about"><section className="store-cta"><div><p className="eyebrow">Find Nilam near you</p><h2>Come in, take your time.</h2><p>Find a warm welcome and pieces you can feel in person.</p></div><Link to="/pages/stores" className="button button-light"><FiMapPin /> Find a store</Link></section><section className="footer-main"><div className="footer-brand"><Link className="brand" to="/">nilam<span>.</span></Link><p>Modest pieces, thoughtfully made for the rhythm of your life.</p><div><a href="#instagram" aria-label="Instagram"><FiInstagram /></a><a href="#contact" aria-label="WhatsApp"><FiMessageCircle /></a></div></div><div><h3>Shop</h3><Link to="/collections/new-arrival">New arrival</Link><Link to="/collections/scarves">Scarves</Link><Link to="/collections/modest-apparel">Modest apparel</Link><Link to="/collections/sarimbit">Family sets</Link></div><div><h3>Help</h3><a href="mailto:hello@nilam.id">Contact us</a><Link to="/pages/stores">Store locator</Link><Link to="/pages/terms">Shipping & returns</Link><Link to="/pages/privacy">Care guide</Link></div><form className="newsletter" onSubmit={subscribe}><h3>Stay in the loop</h3><p>New collections, gentle reminders, and special offers—sent occasionally.</p><label><span className="sr-only">Email address</span><input type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="Your email address" required /><button aria-label="Subscribe"><FiArrowRight /></button></label>{message && <p role="status">{message}</p>}</form></section><section className="footer-bottom"><span>© 2026 Nilam Indonesia</span><div><Link to="/pages/terms">Terms</Link><Link to="/pages/privacy">Privacy</Link></div><span>Made with care in Indonesia</span></section></footer>
}
