import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Header } from '../components/Header'
import { Footer } from '../components/Footer'
import './content-pages.css'

type Store = { id: string; name: string; address: string; city: string; province: string; phone?: string }
type StoreResponse = Store[] | { items: Store[] }
function Frame({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <><Header /><main className="catalogue"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><div className="content-page">{children}</div></main><Footer /></> }
export function StoresPage() { const [q, setQ] = useState(''); const [stores, setStores] = useState<Store[]>([]); const [state, setState] = useState('Loading stores…'); useEffect(() => { const timer = window.setTimeout(() => { fetch(`/api/stores?q=${encodeURIComponent(q)}`).then(response => response.ok ? response.json() : Promise.reject()).then((body: StoreResponse) => { const items = Array.isArray(body) ? body : body.items; setStores(items); setState(items.length ? '' : 'No stores matched your search.') }).catch(() => setState('Store locations are temporarily unavailable.')) }, 200); return () => window.clearTimeout(timer) }, [q]); return <Frame eyebrow="Visit us" title="Find a Nilam store"><label className="store-search">Search by city or province<input value={q} onChange={event => setQ(event.target.value)} placeholder="Jakarta, Bandung…" /></label>{state && <p>{state}</p>}<div className="store-list">{stores.map(store => <article key={store.id}><h2>{store.name}</h2><p>{store.address}<br />{store.city}, {store.province}</p>{store.phone && <a href={`tel:${store.phone}`}>{store.phone}</a>}</article>)}</div></Frame> }
const copy = { about: ['The Nilam way', 'Quiet confidence, worn your way.', 'Nilam creates original modest pieces for everyday movement, meaningful gatherings, and the small rituals in between. We choose comfort, thoughtful proportions, and enduring colours over fleeting noise.'], terms: ['Shopping with Nilam', 'Terms & returns', 'Orders are subject to availability and confirmation. We will publish final delivery, payment, exchange, and return terms here before checkout is enabled. For help with an existing order, please contact our customer-care team.'], privacy: ['Your information', 'Privacy', 'We use the details you share to provide requested services, such as newsletter updates and orders. We do not sell personal information. This page will be expanded with the final retention, cookie, and customer-rights policy before public checkout.'] } as const
export function ContentPage({ page }: { page: keyof typeof copy }) { const [eyebrow, title, text] = copy[page]; return <Frame eyebrow={eyebrow} title={title}><p className="content-copy">{text}</p><Link className="button" to="/collections/all">Browse the collection</Link></Frame> }
