import { useEffect, useState } from 'react'
import { FiChevronDown, FiHeart, FiMenu, FiSearch, FiShoppingBag, FiUser, FiX } from 'react-icons/fi'

const menuGroups = [{ title: 'Shop', links: ['New arrival', 'Best sellers', 'Scarves', 'Modest apparel'] }, { title: 'By occasion', links: ['Daily comfy', 'Workwear', 'Umrah & hajj', 'Family sets'] }, { title: 'Discover', links: ['Style guide', 'Find your shade', 'Store locator', 'Our story'] }]

export function Header() {
  const [menuOpen, setMenuOpen] = useState(false); const [searchOpen, setSearchOpen] = useState(false); const [cartOpen, setCartOpen] = useState(false)
  useEffect(() => { const close = (event: KeyboardEvent) => event.key === 'Escape' && (setMenuOpen(false), setSearchOpen(false), setCartOpen(false)); window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [])
  const closeAll = () => { setMenuOpen(false); setSearchOpen(false); setCartOpen(false) }
  return <><div className="audience-bar"><a href="#discover">Women</a><a href="#discover">Men</a><a href="#discover">Couple</a><a href="#discover">Kids</a><a href="#discover">Sarimbit</a><span>Complimentary shipping on orders over Rp500.000</span></div><header className="header"><button className="menu-toggle" onClick={() => setMenuOpen(true)} aria-label="Open menu"><FiMenu /> <span>Menu</span></button><a className="brand" href="/">nilam<span>.</span></a><nav><a href="#discover">New arrival</a><a href="#categories">Scarves</a><a href="#discover">Apparel</a><a href="#discover">Family sets</a></nav><div className="header-actions"><button onClick={() => setSearchOpen(true)} aria-label="Search"><FiSearch /></button><button aria-label="Saved items"><FiHeart /></button><button onClick={() => setCartOpen(true)} aria-label="Shopping bag" className="cart-action"><FiShoppingBag /><b>0</b></button><button className="account" aria-label="Sign in"><FiUser /><span>Sign in</span></button></div></header><aside className={`side-panel menu-panel ${menuOpen ? 'is-open' : ''}`} aria-hidden={!menuOpen}><div className="panel-head"><span>Explore Nilam</span><button onClick={() => setMenuOpen(false)} aria-label="Close menu"><FiX /></button></div><div className="menu-groups">{menuGroups.map(group => <section key={group.title}><h2>{group.title}</h2>{group.links.map(link => <a key={link} href="#discover" onClick={() => setMenuOpen(false)}>{link}<FiChevronDown /></a>)}</section>)}</div><div className="panel-promo"><p className="eyebrow">Nilam journal</p><strong>Dress with ease, keep with care.</strong><a href="#about">Read our story →</a></div></aside><aside className={`side-panel search-panel ${searchOpen ? 'is-open' : ''}`} aria-hidden={!searchOpen}><div className="panel-head"><span>Search</span><button onClick={() => setSearchOpen(false)} aria-label="Close search"><FiX /></button></div><form className="overlay-search" onSubmit={event => event.preventDefault()}><FiSearch /><input autoFocus={searchOpen} placeholder="Search scarves, dresses, sets..." /><button>Search</button></form><p className="search-hint">Try “voal scarf”, “family set”, or “travel prayer set”</p></aside><aside className={`side-panel cart-panel ${cartOpen ? 'is-open' : ''}`} aria-hidden={!cartOpen}><div className="panel-head"><span>Your bag <small>(0)</small></span><button onClick={() => setCartOpen(false)} aria-label="Close shopping bag"><FiX /></button></div><div className="empty-cart"><FiShoppingBag /><h2>Your bag is waiting</h2><p>Discover pieces made for every day and every meaningful occasion.</p><a className="button" href="#discover" onClick={() => setCartOpen(false)}>Continue shopping</a></div></aside>{(menuOpen || searchOpen || cartOpen) && <button className="scrim" aria-label="Close overlay" onClick={closeAll} />}</>
}
